name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install libgit2
      run: sudo apt-get install libgit2-dev
    - name: make
      working-directory: demo
      run: ARCH=linux make
    - name: make test
      working-directory: demo
      run: ARCH=linux make test
