name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: get libgit2
      run: sudo apt install libgit2-dev
    - name: make
      working-directory: demo
      run: make
    - name: make test
      working-directory: demo
      run: make test
